engines:
    apexmetrics:
        enabled: true
        config:
            rulesets: "./tools/codeclimate/apex/apexunit.xml,./tools/codeclimate/apex/complexity.xml,./tools/codeclimate/apex/performance.xml,./tools/codeclimate/apex/security.xml,./tools/codeclimate/apex/style.xml"
        exclude_paths:
            - "**Tests.cls"
ratings:
    paths:
        - "**.cls"
        - "**.trigger"
